name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, master]

permissions:
  contents: read

jobs:
  pr-check:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore netconsoleappovning.sln

      - name: Build
        run: dotnet build netconsoleappovning.sln --configuration Release --no-restore

      - name: Test
        if: |
          hashFiles('**/*Tests*.csproj') != '' ||
          hashFiles('**/*.Tests.csproj') != '' ||
          hashFiles('**/Tests/*.csproj') != ''
        run: dotnet test netconsoleapp.sln --configuration Release --no-build --verbosity normal
