﻿name: Notify Discord

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, closed]

jobs:
  push_notify:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord on push
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Willes bot"
          avatarUrl: "https://img.favpng.com/17/1/5/manchester-united-logo-png-png-favpng-6R3Xfm9rg1NsU8naJahynJsyD.jpg"
          text: "Jag vill inte va willes bot"
          title: "Push till main"
          description: "📦 Repo: ${{ github.repository }}\nAv: **${{ github.actor }}**\nCommit: `${{ github.sha }}`"
          color: "#2ecc71"